Repository U-is-Ni-in-Korea/Server-United, pull requests merged in 2023-08, with the labels that each got.

#112 feat(111): Separate game creation function
  src/main/java/com/universe/uni/service/GameService.java
Labels: feat, 진수🦂, size/L

#113 feat(110): mission category attribute change
  src/main/java/com/universe/uni/domain/MissionTool.java
  src/main/java/com/universe/uni/domain/entity/MissionCategory.java
  src/main/java/com/universe/uni/domain/entity/convertor/MissionToolAttributeConverter.java
Labels: feat, 진수🦂, size/M

#115 [feat] 승부 기록 API 수정
  src/main/java/com/universe/uni/controller/ShortGameController.java
  src/main/java/com/universe/uni/dto/response/GameReportResponseDto.java
  src/main/java/com/universe/uni/dto/response/MissionCategoryDto.java
  src/main/java/com/universe/uni/exception/dto/ErrorType.java
  src/main/java/com/universe/uni/service/GameService.java
Labels: size/M

#117 chore: Fix Ci
  .github/workflows/ci_checker_on_main_push.yml
  .github/workflows/gradle-task.yml
  .github/workflows/pr_checker.yml
Labels: size/L
