Repository U-is-Ni-in-Korea/Server-United, pull requests merged in 2023-07, with the labels that each got.

#16 #14 [feat] Spring Rest Controller Advice 구현
  src/main/java/com/universe/uni/controller/ControllerExceptionAdvice.java
  src/main/java/com/universe/uni/exception/ApiException.java
  src/main/java/com/universe/uni/exception/BadRequestException.java
  src/main/java/com/universe/uni/exception/ConflictException.java
  src/main/java/com/universe/uni/exception/NotFoundException.java
  src/main/java/com/universe/uni/exception/UnauthorizedException.java
  src/main/java/com/universe/uni/exception/dto/ErrorResponse.java
  src/main/java/com/universe/uni/exception/dto/ErrorType.java
Labels: feat, pull request🔥, 영주🐼, size/L

#18 feat: Update pr_checker.yml
  .github/workflows/pr_checker.yml
Labels: size/S

#19 feat: Update Entity
  src/main/java/com/universe/uni/domain/MissionType.java
  src/main/java/com/universe/uni/domain/entity/MissionCategory.java
  src/main/java/com/universe/uni/domain/entity/RoundGame.java
  src/main/java/com/universe/uni/domain/entity/RoundHistory.java
  src/main/java/com/universe/uni/domain/entity/RoundMission.java
  src/main/java/com/universe/uni/domain/entity/convertor/MissionTypeAttributeConverter.java
Labels: size/L

#24 feat: cd process
  scripts/run_new.sh
  src/main/java/com/universe/uni/UniApplication.java
Labels: size/XS

#25 chore: deploy
  .github/workflows/cd_on_main.yml
  appspec.yml
Labels: size/S

#22 #20 [feat] 소원권 입력 Api 구현
  src/main/java/com/universe/uni/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/universe/uni/controller/ControllerExceptionAdvice.java
  src/main/java/com/universe/uni/controller/WishCouponController.java
  src/main/java/com/universe/uni/domain/entity/WishCoupon.java
  src/main/java/com/universe/uni/dto/request/UpdateWishCouponRequestDto.java
  src/main/java/com/universe/uni/dto/response/UpdateWishCouponResponseDto.java
  src/main/java/com/universe/uni/exception/dto/ErrorType.java
  src/main/java/com/universe/uni/repository/WishCouponRepository.java
  src/main/java/com/universe/uni/service/WishCouponService.java
Labels: feat, pull request🔥, 영주🐼, size/L

#28 #27 [feat] 소원권 상세보기 Api 구현
  src/main/java/com/universe/uni/controller/WishCouponController.java
  src/main/java/com/universe/uni/dto/response/WishCouponResponseDto.java
  src/main/java/com/universe/uni/service/WishCouponService.java
Labels: feat, pull request🔥, 영주🐼, size/M

#31 #30 [feat] 소원권 사용하기 Api 구현
  src/main/java/com/universe/uni/controller/WishCouponController.java
  src/main/java/com/universe/uni/domain/entity/WishCoupon.java
  src/main/java/com/universe/uni/service/WishCouponService.java
Labels: feat, pull request🔥, 영주🐼, size/S

#34 Update README.md
  README.md
Labels: size/S

#26 feat: Kakao Auth
  build.gradle
  src/main/java/com/universe/uni/config/AuthConfig.java
  src/main/java/com/universe/uni/config/FeignConfig.java
  src/main/java/com/universe/uni/controller/AuthController.java
  src/main/java/com/universe/uni/dto/AuthTokenDto.java
  src/main/java/com/universe/uni/external/GoogleApiClient.java
  src/main/java/com/universe/uni/external/GoogleAuthClient.java
  src/main/java/com/universe/uni/external/KakaoApiClient.java
  src/main/java/com/universe/uni/external/KakaoAuthClient.java
  src/main/java/com/universe/uni/external/request/GoogleAuthRequest.java
  src/main/java/com/universe/uni/external/request/KakaoAuthRequest.java
  src/main/java/com/universe/uni/external/response/GoogleAccessTokenResponse.java
  src/main/java/com/universe/uni/external/response/GoogleUserInfoResponse.java
  src/main/java/com/universe/uni/external/response/KakaoAuthResponse.java
  src/main/java/com/universe/uni/external/response/KakaoUserResponse.java
  src/main/java/com/universe/uni/repository/GoogleRepository.java
  src/main/java/com/universe/uni/repository/KakaoRepository.java
  src/main/java/com/universe/uni/repository/RemoteGoogleRepository.java
  src/main/java/com/universe/uni/repository/RemoteKakaoRepository.java
  src/main/java/com/universe/uni/repository/UserRepository.java
  src/main/java/com/universe/uni/service/AuthService.java
  src/main/java/com/universe/uni/service/AuthServiceContract.java
  src/main/java/com/universe/uni/service/JwtManager.java
Labels: feat, pull request🔥, 진수🦂, size/L

#37 #32 [feat] 미션 카테고리 상세 조회하기 Api 구현
  src/main/java/com/universe/uni/controller/MissionController.java
  src/main/java/com/universe/uni/dto/response/MissionCategoryResponseDto.java
  src/main/java/com/universe/uni/dto/response/MissionContentResponseDto.java
  src/main/java/com/universe/uni/repository/MissionContentRepository.java
  src/main/java/com/universe/uni/service/MissionService.java
Labels: feat, pull request🔥, 영주🐼, size/L

#38 #32 [feat] 미션 카테고리 전체 조회하기 Api 구현
  src/main/java/com/universe/uni/controller/MissionController.java
  src/main/java/com/universe/uni/service/MissionService.java
Labels: feat, pull request🔥, 영주🐼, size/S

#40 #39 [feat] 소원권 관련 Api Response 수정
  src/main/java/com/universe/uni/controller/WishCouponController.java
  src/main/java/com/universe/uni/dto/response/WishCouponDto.java
  src/main/java/com/universe/uni/dto/response/WishCouponResponseDto.java
  src/main/java/com/universe/uni/service/WishCouponService.java
Labels: feat, 영주🐼, size/M

#41 #29 [feat] 유저 소원권 전체 조회하기 Api 구현
  src/main/java/com/universe/uni/controller/UserController.java
  src/main/java/com/universe/uni/controller/WishCouponController.java
  src/main/java/com/universe/uni/dto/response/UserWishCouponResponseDto.java
  src/main/java/com/universe/uni/repository/UserRepository.java
  src/main/java/com/universe/uni/repository/WishCouponRepository.java
  src/main/java/com/universe/uni/service/UserService.java
Labels: feat, pull request🔥, 영주🐼

#43 #42 [feat] 홈 조회하기 Api 구현
  src/main/java/com/universe/uni/controller/HomeController.java
  src/main/java/com/universe/uni/dto/CoupleDto.java
  src/main/java/com/universe/uni/dto/MissionContentDto.java
  src/main/java/com/universe/uni/dto/RoundMissionDto.java
  src/main/java/com/universe/uni/dto/ShortGameDto.java
  src/main/java/com/universe/uni/dto/WishCouponDto.java
  src/main/java/com/universe/uni/dto/response/CreateShortGameResponseDto.java
  src/main/java/com/universe/uni/dto/response/HomeResponseDto.java
  src/main/java/com/universe/uni/dto/response/MissionCategoryResponseDto.java
  src/main/java/com/universe/uni/dto/response/UserWishCouponResponseDto.java
  src/main/java/com/universe/uni/dto/response/WishCouponResponseDto.java
  src/main/java/com/universe/uni/exception/dto/ErrorType.java
  src/main/java/com/universe/uni/repository/CoupleRepository.java
  src/main/java/com/universe/uni/repository/GameRepository.java
  src/main/java/com/universe/uni/repository/RoundGameRepository.java
  src/main/java/com/universe/uni/repository/UserGameHistoryRepository.java
  src/main/java/com/universe/uni/repository/UserRepository.java
  src/main/java/com/universe/uni/service/HomeService.java
  src/main/java/com/universe/uni/service/MissionService.java
  src/main/java/com/universe/uni/service/UserService.java
  src/main/java/com/universe/uni/service/WishCouponService.java
Labels: feat, pull request🔥, 영주🐼

#45 #44 [feat] 홈 response에 디데이 필드 추가
  src/main/java/com/universe/uni/dto/response/HomeResponseDto.java
  src/main/java/com/universe/uni/service/HomeService.java
Labels: feat, pull request🔥, 영주🐼, size/S

#47 [feat] 한판 승부 기록하기 API 구현
  src/main/java/com/universe/uni/controller/ShortGameController.java
  src/main/java/com/universe/uni/domain/entity/Game.java
  src/main/java/com/universe/uni/domain/entity/RoundGame.java
  src/main/java/com/universe/uni/domain/entity/RoundMission.java
  src/main/java/com/universe/uni/domain/entity/UserGameHistory.java
  src/main/java/com/universe/uni/domain/entity/WishCoupon.java
  src/main/java/com/universe/uni/dto/RoundMissionDto.java
  src/main/java/com/universe/uni/dto/request/EnterGameResultDto.java
  src/main/java/com/universe/uni/dto/response/GameReportResponseDto.java
  src/main/java/com/universe/uni/dto/response/MissionCategoryDto.java
  src/main/java/com/universe/uni/dto/response/RoundMissionContentDto.java
  src/main/java/com/universe/uni/exception/dto/ErrorType.java
  src/main/java/com/universe/uni/repository/RoundMissionRepository.java
  src/main/java/com/universe/uni/repository/WishCouponRepository.java
  src/main/java/com/universe/uni/service/GameService.java
  src/main/java/com/universe/uni/service/WishCouponService.java
Labels: feat, pull request🔥, 지연🐰, size/L

#54 feat: 커플 생성 및 연결 기능 작성
  src/main/java/com/universe/uni/controller/CoupleController.java
  src/main/java/com/universe/uni/domain/InviteCodeStrategy.java
  src/main/java/com/universe/uni/domain/RandomInviteCodeGenerator.java
  src/main/java/com/universe/uni/domain/entity/Couple.java
  src/main/java/com/universe/uni/dto/request/CreateCoupleRequestDto.java
  src/main/java/com/universe/uni/dto/request/JoinCoupleRequestDto.java
  src/main/java/com/universe/uni/exception/dto/ErrorType.java
  src/main/java/com/universe/uni/repository/CoupleRepository.java
  src/main/java/com/universe/uni/service/CoupleService.java
  src/main/java/com/universe/uni/service/CoupleServiceContract.java
Labels: size/L

#53 Feature/user
  build.gradle
  src/main/java/com/universe/uni/controller/CoupleController.java
  src/main/java/com/universe/uni/controller/UserController.java
  src/main/java/com/universe/uni/domain/InviteCodeStrategy.java
  src/main/java/com/universe/uni/domain/RandomInviteCodeGenerator.java
  src/main/java/com/universe/uni/domain/entity/Couple.java
  src/main/java/com/universe/uni/dto/UserDto.java
  src/main/java/com/universe/uni/dto/request/CreateCoupleRequestDto.java
  src/main/java/com/universe/uni/dto/request/JoinCoupleRequestDto.java
  src/main/java/com/universe/uni/dto/request/UpdateUserNicknameRequestDto.java
  src/main/java/com/universe/uni/dto/response/CoupleDto.java
  src/main/java/com/universe/uni/exception/dto/ErrorType.java
  src/main/java/com/universe/uni/mapper/CoupleMapper.java
  src/main/java/com/universe/uni/mapper/UserMapper.java
  src/main/java/com/universe/uni/repository/CoupleRepository.java
  src/main/java/com/universe/uni/service/CoupleService.java
  src/main/java/com/universe/uni/service/CoupleServiceContract.java
  src/main/java/com/universe/uni/service/JwtManager.java
  src/main/java/com/universe/uni/service/UserService.java
  src/main/java/com/universe/uni/service/UserServiceContract.java
Labels: size/L

#55 chore: fix switch server port script
  scripts/switch.sh
Labels: size/XS

#57 [feat] 미션 카테고리 관련 response에 rule 추가
  src/main/java/com/universe/uni/domain/entity/MissionCategory.java
  src/main/java/com/universe/uni/dto/response/MissionCategoryResponseDto.java
  src/main/java/com/universe/uni/service/MissionService.java
Labels: feat, pull request🔥, 영주🐼, size/S

#60 [feat] Game 레포지토리 Jpa 쿼리 수정 (영주 인간 지능 이슈)
  src/main/java/com/universe/uni/repository/GameRepository.java
  src/main/java/com/universe/uni/service/HomeService.java
Labels: pull request🔥, 영주🐼, size/XS, HOTFIX🚨

#61 [feat] 승부 중단하기 API
  src/main/java/com/universe/uni/controller/ShortGameController.java
  src/main/java/com/universe/uni/domain/entity/RoundGame.java
  src/main/java/com/universe/uni/domain/entity/RoundMission.java
  src/main/java/com/universe/uni/domain/entity/WishCoupon.java
  src/main/java/com/universe/uni/service/GameService.java
Labels: feat, pull request🔥, 지연🐰, size/S

#62 [feat] 승부 히스토리 전체 조회하기 api 구현
  src/main/java/com/universe/uni/controller/HistoryController.java
  src/main/java/com/universe/uni/dto/MissionResultDto.java
  src/main/java/com/universe/uni/dto/response/GameHistoryResponseDto.java
  src/main/java/com/universe/uni/exception/dto/ErrorType.java
  src/main/java/com/universe/uni/repository/RoundMissionRepository.java
  src/main/java/com/universe/uni/repository/UserGameHistoryRepository.java
  src/main/java/com/universe/uni/service/HistoryService.java
Labels: feat, pull request🔥, 영주🐼, size/L

#65 chore: Add swagger
  build.gradle
  src/main/java/com/universe/uni/config/SwaggerConfig.java
  src/main/java/com/universe/uni/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/universe/uni/controller/AuthController.java
  src/main/java/com/universe/uni/controller/docs/AuthControllerContract.java
Labels: size/L

#64 [feat] Jwt에 있는 userId로 User 가져오는 util 구현
  src/main/java/com/universe/uni/exception/dto/ErrorType.java
  src/main/java/com/universe/uni/service/GameService.java
  src/main/java/com/universe/uni/service/UserUtil.java
Labels: feat, 지연🐰, size/M

#68 docs: Update README.md
  README.md
Labels: size/S

#71 [feat] 승부 생성하기 api 수정
  src/main/java/com/universe/uni/dto/response/CreateShortGameResponseDto.java
  src/main/java/com/universe/uni/service/GameService.java
Labels: size/S

#72 [feat] 홈/히스토리 Api userId 로직 및 Game 비어있을 때 null처리 수정
  src/main/java/com/universe/uni/repository/GameRepository.java
  src/main/java/com/universe/uni/service/HistoryService.java
  src/main/java/com/universe/uni/service/HomeService.java
Labels: fix, pull request🔥, 영주🐼, size/M

#74 [feat] HttpStatus No Content일 경우 204로 내려주기
  src/main/java/com/universe/uni/controller/WishCouponController.java
Labels: feat, pull request🔥, 영주🐼

#67 chore: Add Sentry captureException
  src/main/java/com/universe/uni/controller/ControllerExceptionAdvice.java
Labels: feat, pull request🔥, 영주🐼, size/XS

#76 [feat] 히스토리 전체조회하기 Api response 안 내려오는 것 수정
  src/main/java/com/universe/uni/controller/ShortGameController.java
  src/main/java/com/universe/uni/service/HistoryService.java
Labels: feat, pull request🔥, 영주🐼, size/S

#77 [feat] 히스토리 전체 조회하기 Api response에 winner 필드 추가
  src/main/java/com/universe/uni/dto/response/GameHistoryResponseDto.java
  src/main/java/com/universe/uni/repository/UserRepository.java
  src/main/java/com/universe/uni/service/HistoryService.java
Labels: feat, pull request🔥, 영주🐼, size/M

#78 fix: Fix Login logic
  scripts/run_new.sh
  src/main/java/com/universe/uni/controller/AuthController.java
  src/main/java/com/universe/uni/controller/docs/AuthControllerContract.java
Labels: size/L

#79 feat: Update cd script
  appspec.yml
  scripts/run_new.sh
Labels: size/XS

#80 fix: Fix SNS Auth Method
  src/main/java/com/universe/uni/service/AuthService.java
  src/main/java/com/universe/uni/service/AuthServiceContract.java
Labels: size/S

#81 [feat] 히스토리 response에 content 필드 추가 및 날짜/시간 포멧 수정
  src/main/java/com/universe/uni/dto/MissionResultDto.java
  src/main/java/com/universe/uni/service/HistoryService.java
Labels: feat, pull request🔥, 영주🐼, size/S

#82 chore: Troubleshooting aws script quiescing
  appspec.yml
  scripts/profile.sh
  scripts/start.sh
  scripts/stop.sh
  scripts/switch.sh
Labels: size/M

#83 chore: Modify Deployment Script
  appspec.yml
  scripts/health_check.sh
  scripts/profile.sh
  scripts/start.sh
  scripts/stop.sh
  scripts/switch.sh
Labels: size/M

#84 [feat] 소원권 받아오는 JPA 수정
  src/main/java/com/universe/uni/repository/WishCouponRepository.java
  src/main/java/com/universe/uni/service/WishCouponService.java
Labels: feat, pull request🔥, 영주🐼, size/M

#86 [feat] 홈 response에 커플의 userId 내려주기
  build.gradle
  src/main/java/com/universe/uni/dto/response/HomeResponseDto.java
  src/main/java/com/universe/uni/repository/UserRepository.java
  src/main/java/com/universe/uni/service/HomeService.java
Labels: feat, pull request🔥, 영주🐼, size/S

#88 [feat] 마이페이지 Api 구현
  src/main/java/com/universe/uni/controller/UserController.java
  src/main/java/com/universe/uni/dto/response/ProfileResponseDto.java
  src/main/java/com/universe/uni/service/UserService.java
  src/main/java/com/universe/uni/service/UserServiceContract.java
Labels: feat, pull request🔥, 영주🐼, size/M

#91 [feat] 소원권 입력 공백 처리
  src/main/java/com/universe/uni/service/GameService.java
  src/main/java/com/universe/uni/service/WhitespaceNormalizer.java
  src/main/java/com/universe/uni/service/WishCouponService.java
Labels: feat, pull request🔥, 영주🐼, size/M

#93 [feat] Update Profile API 수정
  src/main/java/com/universe/uni/controller/UserController.java
  src/main/java/com/universe/uni/dto/request/UpdateUserProfileRequestDto.java
Labels: feat, 지연🐰, size/S

#95 feat: 상대 연결 확인하기 API
  src/main/java/com/universe/uni/controller/CoupleController.java
  src/main/java/com/universe/uni/dto/response/CoupleConnectionResponseDto.java
  src/main/java/com/universe/uni/service/CoupleService.java
  src/main/java/com/universe/uni/service/CoupleServiceContract.java
Labels: feat, pull request🔥, 지연🐰, 영주🐼, size/M

#97 feat: Update ShortGame Report API
  src/main/java/com/universe/uni/service/GameService.java
Labels: size/XS

#98 [feat] 유저소원권조회 / 히스토리 response 정렬 수정
  src/main/java/com/universe/uni/service/HistoryService.java
  src/main/java/com/universe/uni/service/UserService.java
Labels: feat, pull request🔥, 영주🐼, size/S

#101 [feat] 디데이 계산 로직 수정, 유저의 소원권 조회에서 빈 콘텐츠 제외하기
  src/main/java/com/universe/uni/service/HomeService.java
  src/main/java/com/universe/uni/service/UserService.java
Labels: feat, pull request🔥, 영주🐼, size/S

#102 fix: Fix newWishCoupon logic
  src/main/java/com/universe/uni/service/UserService.java
Labels: feat, pull request🔥, 영주🐼, size/XS

#106 feat: Add random image to wish coupon
  src/main/java/com/universe/uni/service/WishCouponService.java
Labels: feat, 지연🐰, size/S

#107 feat: Add delete user
  scripts/health_check.sh
  scripts/start.sh
  scripts/stop.sh
  src/main/java/com/universe/uni/config/AuthConfig.java
  src/main/java/com/universe/uni/controller/ControllerExceptionAdvice.java
  src/main/java/com/universe/uni/controller/CoupleController.java
  src/main/java/com/universe/uni/controller/UserController.java
  src/main/java/com/universe/uni/external/KakaoApiClient.java
  src/main/java/com/universe/uni/external/request/KakaoUnlinkRequest.java
  src/main/java/com/universe/uni/external/response/KakaoUnlinkResponse.java
  src/main/java/com/universe/uni/repository/KakaoRepository.java
  src/main/java/com/universe/uni/repository/RemoteKakaoRepository.java
  src/main/java/com/universe/uni/service/AuthService.java
  src/main/java/com/universe/uni/service/AuthServiceContract.java
  src/main/java/com/universe/uni/service/CoupleService.java
  src/main/java/com/universe/uni/service/CoupleServiceContract.java
  src/main/java/com/universe/uni/service/UserService.java
  src/main/java/com/universe/uni/service/UserServiceContract.java
Labels: size/L

#108 fix: Changing a Nondisruptive Deployment Script
  scripts/health_check.sh
  scripts/start.sh
  scripts/stop.sh
Labels: size/S
