Repository U-is-Ni-in-Korea/Server-United, pull requests merged in 2023-09, with the labels that each got.

#119 [Feat] 게임 생성 시 동시성 문제 해결
  src/main/java/com/universe/uni/controller/ControllerExceptionAdvice.java
  src/main/java/com/universe/uni/domain/entity/Couple.java
  src/main/java/com/universe/uni/repository/CoupleRepository.java
  src/main/java/com/universe/uni/service/GameService.java
Labels: size/M

#124 [Fix] 소원권 상세보기 response nickname 수정
  src/main/java/com/universe/uni/service/WishCouponService.java
Labels: fix, 영주🐼, size/XS

#122 [Feat] mission content recommend time
  .github/workflows/ci_checker_on_main_push.yml
  src/main/java/com/universe/uni/domain/entity/MissionContent.java
  src/main/java/com/universe/uni/dto/MissionContentDto.java
  src/main/java/com/universe/uni/dto/response/RoundMissionContentDto.java
  src/main/java/com/universe/uni/service/MissionService.java
Labels: size/L

#127 커플 연결 관련 수정
  src/main/java/com/universe/uni/controller/CoupleController.java
  src/main/java/com/universe/uni/exception/dto/ErrorType.java
  src/main/java/com/universe/uni/repository/UserRepository.java
  src/main/java/com/universe/uni/service/CoupleService.java
  src/main/java/com/universe/uni/service/CoupleServiceContract.java
Labels: size/M

#128 [Feat] util of swagger
  src/main/java/com/universe/uni/config/SecurityConfig.java
  src/main/java/com/universe/uni/config/SwaggerConfig.java
  src/main/java/com/universe/uni/controller/AuthController.java
  src/main/java/com/universe/uni/controller/docs/AuthControllerContract.java
  src/main/java/com/universe/uni/service/AuthService.java
  src/main/java/com/universe/uni/service/AuthServiceContract.java
Labels: size/L

#130 docs: 109 couple controller
  src/main/java/com/universe/uni/controller/CoupleController.java
  src/main/java/com/universe/uni/controller/docs/AuthControllerContract.java
  src/main/java/com/universe/uni/controller/docs/CoupleControllerContract.java
  src/main/java/com/universe/uni/dto/request/CreateCoupleRequestDto.java
  src/main/java/com/universe/uni/dto/request/JoinCoupleRequestDto.java
  src/main/java/com/universe/uni/dto/response/CoupleConnectionResponseDto.java
Labels: size/L

#131 [Feat] 유저의 미션은 미션 카테고리에 따라 서로 다르거나 같은 미션을 제공한다.
  src/main/java/com/universe/uni/config/SwaggerConfig.java
  src/main/java/com/universe/uni/domain/entity/MissionCategory.java
  src/main/java/com/universe/uni/service/GameService.java
Labels: size/M

#136 [Feat] 최종승부결과 확인하기 관련 API 수정
  src/main/java/com/universe/uni/domain/entity/RoundMission.java
  src/main/java/com/universe/uni/repository/UserGameHistoryRepository.java
  src/main/java/com/universe/uni/service/GameService.java
Labels: size/M
